=== oldulov/cfeditor/src/cfeditorxtext/edu.kit.scc.cfeditor.cfengine/src/edu/kit/scc/cfeditor/cfengine/definitions/Definitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.kit.edu/scc/Cfeditor"
	xmlns:tns="http://www.kit.edu/scc/Cfeditor" elementFormDefault="qualified">

    <element name="part" type="tns:partType"></element>

	<complexType name="partType">
		<sequence>
			<element ref="tns:body" minOccurs="1" maxOccurs="1"></element>
			<element ref="tns:bundle" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>

    <element name="body" type="tns:bodyType">
    	<unique name="bodyComponentName">
			<selector xpath="tns:component" />
			<field xpath="@name" />
		</unique>
	</element>

	<element name="bundle" type="tns:bundleType">
		<unique name="bundleComponentName">
			<selector xpath="tns:component" />
			<field xpath="@name" />
		</unique>
	</element>

	<element name="component" type="tns:componentType"></element>

	<element name="promisetype" type="tns:promisetypeType"></element>

	<complexType name="bodyType">
		<sequence>
			<element ref="tns:component" maxOccurs="unbounded"></element>
			<element ref="tns:promisetype" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="bundleType">
		<sequence>
			<element ref="tns:component" maxOccurs="unbounded"></element>
			<element ref="tns:promisetype" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="componentType">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="promisetypes" type="tns:typeList" use="required"></attribute>
	</complexType>

	<complexType name="promisetypeType">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="type" type="tns:dataType" use="required"></attribute>
		<attribute name="range" type="string" use="optional"></attribute>
	</complexType>

	<simpleType name="dataType">
		<restriction base="string">
			<enumeration value="INT"></enumeration>
			<enumeration value="STRING"></enumeration>
			<enumeration value="SLIST"></enumeration>
			<enumeration value="OPTION"></enumeration>
			<enumeration value="IRANGE"></enumeration>
			<enumeration value="REAL"></enumeration>
		</restriction>
	</simpleType>
	
	<simpleType name="typeList">
		<list itemType="string"></list>
	</simpleType>
</schema>

=== oldulov/cfeditor/src/cfeditorxtext/edu.kit.scc.cfeditor.cfengine/src/edu/kit/scc/cfeditor/cfengine/definitions/Definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<part xmlns="http://www.kit.edu/scc/Cfeditor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kit.edu/scc/Cfeditor Definitions.xsd">
  <body>
    <component name="acl" promisetypes="aces acl_directory_inherit acl_method acl_type specify_inherit_aces" />
    <component name="action" promisetypes="action_policy ifelapsed expireafter log_string log_level log_kept log_priority log_repaired log_failed audit background report_level measurement_class" />
    <component name="association" promisetypes="forward_relationship backward_relationship associates" />
    <component name="changes" promisetypes="hash report_changes update_hashes report_diffs" />
    <component name="classes" promisetypes="promise_repaired repair_failed repair_denied repair_timeout promise_kept cancel_kept cancel_repaired cancel_notkept persist_time timer_policy" />
    <component name="contain" promisetypes="useshell umask exec_owner exec_group exec_timeout chdir chroot preview no_output" />
    <component name="copy_from" promisetypes="source servers collapse_destination_dir compare copy_backup encrypt check_root copylink_patterns copy_size findertype linkcopy_patterns force_update force_ipv4 portnumber preserve purge stealth timeout trustkey type_check verify" />
    <component name="database_server" promisetypes="db_server_owner db_server_password db_server_host db_server_type db_server_connection_db" />
    <component name="delete" promisetypes="dirlinks rmdirs" />
    <component name="delete_select" promisetypes="delete_if_startwith_from_list delete_if_not_startwith_from_list delete_if_match_from_list delete_if_not_match_from_list delete_if_contains_from_list delete_if_not_contains_from_list" />
    <component name="depth_search" promisetypes="depth exclude_dirs include_basedir include_dirs rmdeadlinks traverse_links xdev" />
    <component name="edit_defaults" promisetypes="edit_backup empty_file_before_editing max_file_size recognize_join" />
    <component name="edit_field" promisetypes="allow_blank_fields extend_fields field_operation field_separator field_value select_field value_separator" />
    <component name="environment_interface" promisetypes="env_addresses env_name env_network" />
    <component name="environment_resources" promisetypes="env_cpus env_memory env_disk env_baseline env_spec_file" />
    <component name="file_select" promisetypes="leaf_name path_name search_mode search_size search_owners search_groups search_bsdflags ctime mtime atime exec_regex exec_program file_types issymlinkto file_result" />
    <component name="infer" promisetypes="pre_assoc_pattern post_assoc_pattern inference" />
    <component name="insert_select" promisetypes="insert_if_startwith_from_list insert_if_not_startwith_from_list insert_if_match_from_list insert_if_not_match_from_list insert_if_contains_from_list insert_if_not_contains_from_list" />
    <component name="link_from" promisetypes="source link_type copy_patterns link_children when_linking_children when_no_source" />
    <component name="location" promisetypes="before_after first_last" />
    <component name="match_value" promisetypes="select_line_matching select_line_matching select_line_number extraction_regex track_growing_file" />
    <component name="mount" promisetypes="edit_fstab mount_type mount_source mount_server mount_options unmount" />
	<component name="package_method" promisetypes="package_add_command package_arch_regex package_changes package_delete_command package_delete_convention package_file_repositories package_installed_regex package_list_arch_regex package_list_command package_list_name_regex package_list_update_command package_list_update_ifelapsed package_list_version_regex package_name_convention package_name_regex package_noverify_regex package_noverify_returncode package_patch_arch_regex package_patch_command package_patch_installed_regex package_patch_list_command package_patch_name_regex package_patch_version_regex package_update_command package_verify_command package_version_regex package_multiline_start" />
    <component name="perms" promisetypes="bsdflags groups mode owners rxdirs" />
    <component name="printfile" promisetypes="file_to_print number_of_lines" />
    <component name="process_count" promisetypes="in_range_define match_range out_of_range_define" />
    <component name="process_select" promisetypes="command pid pgid ppid priority process_owner process_result rsize status stime_range ttime_range tty threads vsize" />
    <component name="rename" promisetypes="disable disable_mode disable_suffix newname rotate" />
    <component name="replace_with" promisetypes="occurrences replace_value" />
    <component name="select_region" promisetypes="include_start_delimiter include_end_delimiter select_start select_end" />
    <component name="service_method" promisetypes="service_type service_args service_autostart_policy service_dependence_chain" />
    <component name="tcp_ip" promisetypes="ipv4_address ipv4_netmask ipv6_address" />
    <component name="transaction" promisetypes="value_kept value_repaired value_notkept" />
    <component name="volume" promisetypes="check_foreign freespace sensible_size sensible_count scan_arrivals" />
    <promisetype name="aces" type="SLIST" range="((user|group):[^:]+:[-=+,rwx()dtTabBpcoD]*(:(allow|deny))?)|((all|mask):[-=+,rwx()]*(:(allow|deny))?)" />
    <promisetype name="acl_directory_inherit" type="OPTION" range="nochange,parent,specify,clear" />
    <promisetype name="acl_method" type="OPTION" range="append,overwrite" />
    <promisetype name="acl_type" type="OPTION" range="generic,posix,ntfs" />
    <promisetype name="action_policy" type="OPTION" range="fix,warn,nop" />
    <promisetype name="allow_blank_fields" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="associates" type="SLIST" range="" />
    <promisetype name="atime" type="IRANGE" range="0,2147483647" />
    <promisetype name="audit" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="background" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="backward_relationship" type="STRING" range="" />
    <promisetype name="before_after" type="OPTION" range="before,after" />
    <promisetype name="bsdflags" type="SLIST" range="[+-]*" />
    <promisetype name="cancel_kept" type="SLIST" range="[a-zA-Z0-9_$()\[\].]+" />
    <promisetype name="cancel_notkept" type="SLIST" range="[a-zA-Z0-9_$()\[\].]+" />
    <promisetype name="cancel_repaired" type="SLIST" range="[a-zA-Z0-9_$()\[\].]+" />
    <promisetype name="chdir" type="STRING" range="&quot;?(([a-zA-Z]:\\.*)|(/.*))" />
    <promisetype name="check_foreign" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="check_root" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="chroot" type="STRING" range="&quot;?(([a-zA-Z]:\\.*)|(/.*))" />
    <promisetype name="collapse_destination_dir" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="command" type="STRING" range="" />
    <promisetype name="compare" type="OPTION" range="atime,mtime,ctime,digest,hash,exists,binary" />
    <promisetype name="copylink_patterns" type="SLIST" range="" />
    <promisetype name="copy_backup" type="OPTION" range="true,false,timestamp" />
    <promisetype name="copy_patterns" type="SLIST" range="" />
    <promisetype name="copy_size" type="IRANGE" range="0,inf" />
    <promisetype name="ctime" type="IRANGE" range="0,2147483647" />
    <promisetype name="db_server_connection_db" type="STRING" range="" />
    <promisetype name="db_server_host" type="STRING" range="" />
    <promisetype name="db_server_owner" type="STRING" range="" />
    <promisetype name="db_server_password" type="STRING" range="" />
    <promisetype name="db_server_type" type="OPTION" range="postgres,mysql" />
    <promisetype name="delete_if_contains_from_list" type="SLIST" range="" />
    <promisetype name="delete_if_match_from_list" type="SLIST" range="" />
    <promisetype name="delete_if_not_contains_from_list" type="SLIST" range="" />
    <promisetype name="delete_if_not_match_from_list" type="SLIST" range="" />
    <promisetype name="delete_if_not_startwith_from_list" type="SLIST" range="" />
    <promisetype name="delete_if_startwith_from_list" type="SLIST" range="" />
    <promisetype name="depth" type="INT" range="0,99999999999" />
    <promisetype name="dirlinks" type="OPTION" range="delete,tidy,keep" />
    <promisetype name="disable" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="disable_mode" type="STRING" range="[0-7augorwxst,+-]+" />
    <promisetype name="disable_suffix" type="STRING" range="" />
    <promisetype name="edit_backup" type="OPTION" range="true,false,timestamp,rotate" />
    <promisetype name="edit_fstab" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="empty_file_before_editing" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="encrypt" type="OPTION" range="true,false,yes,no,on,off" />
    <promisetype name="env_addresses" type="SLIST" range="" />
    <promisetype name="env_baseline" type="STRING" range="&quot;?(([a-zA-Z]:\\.*)|(/.*))" />
    <promisetype name="env_cpus" type="INT" range="0,99999999999" />
    <promisetype name="env_disk" type="INT" range="0,99999999999" />
    <promisetype name="env_memory" type="INT" range="0,99999999999" />
    <promisetype name="env_name" type="STRING" range="" />
    <promisetype name="env_network" type="STRING" range="" />
    <promisetype name="env_spec_file" type="STRING" range="&quot;?(([a-zA-Z]:\\.*)|(/.*))" />
    <promisetype name="exclude_dirs" type="SLIST" range=".*" />
    <promisetype name="exec_group" type="STRING" range="" />
    <promisetype name="exec_owner" type="STRING" range="" />
